apiVersion: apps/v1
kind: Deployment
metadata:
  name: common-deployment
spec:
  replicas: 3  # Number of NGINX pods to run
  selector:
    matchLabels:
      app: common-deployment
  template:
    metadata:
      labels:
        app: common-deployment