jupyterhub:
  proxy:
    service:
      type: ClusterIP
  singleuser:
    defaultUrl: "/lab"
    image:
      name: maverickme22/jupyterhub
      tag: v1.0.7
      pullPolicy: Always
    # lifecycleHooks:
    #   postStart:
    #     exec:
    #       command:
    #         [
    #           "gitpuller",
    #           "https://github.com/maverickme22/jupyter.git",
    #           "main",
    #           "jupyter",
    #         ]