jupyterhub:
  proxy:
    service:
      type: ClusterIP
  singleuser:
    defaultUrl: "/lab"
    image:
      name: maverickme22/jupyterhub
      tag: v2.0.0
      pullPolicy: Always
    storage:
      type: none
    extraEnv:
      GRANT_SUDO: "yes"
      NB_USER: ${USER}
      CHOWN_HOME: 'yes'
      CHOWN_HOME_OPTS: '-R'
    uid: 0
    fsGid: 0
    # lifecycleHooks:
    #   postStart:
    #     exec:
    #       command:
    #         [
    #           "gitpuller",
    #           "https://github.com/maverickme22/jupyter.git",
    #           "main",
    #           "jupyter",
    #         ]