jupyterhub:
  proxy:
    service:
      type: ClusterIP
  singleuser:
    defaultUrl: "/lab"
    image:
      name: maverickme22/jupyterhub
      tag: v1.0.0
    lifecycleHooks:
      postStart:
        exec:
          command:
            [
              "gitpuller",
              "https://github.com/data-8/materials-fa17",
              "master",
              "materials-fa",
            ]