apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-kube-prometheus-stack-resources
  namespace: argocd
  labels:
    app: external-kube-prometheus-stack-resources
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: prometheus
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deployments/services/prometheus-resources/overlays/dev
    repoURL: https://github.com/Maverickme222222/kustomize
    targetRevision: HEAD
  syncPolicy:
    # Override sync policy to ensure ArgoCD can handle the very large CRD files
    # in the kube-prometheus-stack chart. See
    # https://argo-cd.readthedocs.io/en/release-2.4/user-guide/sync-options/#replace-resource-instead-of-applying-changes
    # for more details.
    syncOptions:
      - ServerSideApply=true
      - Replace=true
      - CreateNamespace=true