# Default values for nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

base:
  deploymentName: "nginx-test"
  replicaCount: 2
  containerName: "nginx"

  image:
    repository: nginx
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

