# Default values for base.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: ""
replicaCount: 1
containerName: ""

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

