apiVersion: apps/v1
kind: Deployment
metadata:
  name: common-deployment
  app: nginx
spec:
  replicas: 2 # Update the replica count to 3
  template:
    spec:
      containers:
      - name: common
        image: nginx:latest