kube-prometheus-stack:
  fullnameOverride: kappa-prometheus
  defaultRules:
    create: true
    rules:
      etcd: false
      kubeControllerManager: false
      kubeProxy: false

  alertmanager:
    # Note we configure AlertMgr via an AlertmanagerConfiguration - see
    # templates dir
    enabled: true
    

  prometheus-node-exporter:
    hostRootFsMount:
      enabled: false