kube-prometheus-stack:
  fullnameOverride: kappa-prometheus
  defaultRules:
    create: true
    rules:
      etcd: false
      kubeControllerManager: false
      kubeProxy: false

  alertmanager:
    # Note we configure AlertMgr via an AlertmanagerConfiguration - see
    # templates dir
    enabled: true
    service:
      type: LoadBalancer

  prometheus:
    service:
      type: LoadBalancer

  grafana:
    sidecar:
      dashboards:
        enabled: true
        provider:
          foldersFromFilesStructure: true
  
  kube-state-metrics:
    extraArgs:
      - --metric-labels-allowlist=pods=[app.kubernetes.io/name,app.kubernetes.io/version]
  
  kubeEtcd:
    enabled: false

  # The EKS control plane is not accessible from worker nodes
  kubeControllerManager:
    enabled: false

  # KubeProxy instances listen on localhost for metrics by default
  kubeProxy:
    enabled: false

  # The EKS control plane is not accessible from worker nodes
  kubeScheduler:
    enabled: false

  prometheus-node-exporter:
    hostRootFsMount:
      enabled: false