kube-prometheus-stack:
  fullnameOverride: kappa-prometheus
  defaultRules:
    create: true
    rules:
      etcd: false
      kubeControllerManager: false
      kubeProxy: false

  alertmanager:
    # Note we configure AlertMgr via an AlertmanagerConfiguration - see
    # templates dir
    enabled: true

  grafana:
    sidecar:
      dashboards:
        enabled: true
        provider:
          foldersFromFilesStructure: true
  
  kube-state-metrics:
    extraArgs:
      - --metric-labels-allowlist=pods=[app.kubernetes.io/name,app.kubernetes.io/version]

  prometheus-node-exporter:
    hostRootFsMount:
      enabled: false