apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
namespace: prometheus

helmCharts:
- name: kube-prometheus-stack
  repo: https://github.com/prometheus-community/helm-charts/charts
  version: 0.1.0